### ISSUE TITLE
Repozytorium do zamknięcia

### ISSUE THREAD

**Issue by czogran** [GroupOfRobots/MiniRysRPiOSConfig#1]
Myślę, że lepiej mieć całą dokumentację w jednym miejscu, przeniosłem pliki z tego repozytorium do repo z dokumentacją

https://github.com/GroupOfRobots/MiniRysDocumentation/tree/main/rpi-operating-system   

W następnym kroku będzie można dodać opisy itp. Usunąć aliasy, w wolnej chwili spróbuję popisać co wiem, jeśli ten krok jest OK. Jesli nie, to usunę te pliki z MiniRysDocumentation

**Comment by czogran** [comment]
Nie mogę przepiąć asignee, @Kubaless Kuba zerknij jak będziesz miał chwilę :)

**Comment by Kubaless** [comment]
Dokumentacja to coś innego niż skrypty i pliki konfiguracyjne, niedawno utworzyłem to repo i bym je tak zostawił.
W nim powinny znajdować się skryptu i pliki nie wchodzące w workspace ROSowy, a które są uruchamiane przy starcie systemu. tj preparegpio.sh lub w innych sytuacjach.

**Comment by czogran** [comment]
to podlinkuje w takim razie to repo do dokumentacji.    
ja wolę politykę monorepo, jak najmniej repozytoriów.   
I z tego,  co już obecnie widzę, mamy aż za dużo repozytoriów i nie da się wyłapać gdzie co jest. 
Ale nie będę się upierał.
